### ISSUE TITLE
XZ Utils update

### ISSUE THREAD

**Issue by lanxianmei** [jonathonl/shrinkwrap#5]
Hi, I install **SAIGE** as follow but fail:
**R CMD INSTALL --library=<install_prefix> SAIGE**

**The version xz-5.2.3.tar.bz2 now had updated to xz-5.2.5.tar.bz2. Can you update it in the requirements.txt or just tell me how to update it myself? 
Because it download the specified default version when automated install** 

R CMD INSTALL --library=SAIGE/library SAIGE
* installing *source* package ‘SAIGE’ ...
** using staged installation
Package xz already installed
Downloading https://github.com/statgen/savvy/archive/v2.0.1.tar.gz
  [######################################################################]  100%
Extracting archive SAIGE/thirdParty/cget/cget/build/tmp-ae4bdb72c31945b88fe4ae12c7ec1772/v2.0.1.tar.gz ...
Downloading https://github.com/jonathonl/shrinkwrap/archive/420eb397e31dedc17cae9eecdf33e8fb10e05497.tar.gz
  [######################################################################]  100%
Extracting archive SAIGE/thirdParty/cget/cget/build/tmp-e15721b9b0d245bdb2fe67b0ae6d9e4c/420eb397e31dedc17cae9eecdf33e8fb10e05497.tar.gz ...
Downloading https://tukaani.org/xz/xz-5.2.3.tar.bz2
  [----------------------------------------------------------------------]    0%
Download failed with error 503 for: //tukaani.org/xz/xz-5.2.3.tar.bz2
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
* removing ‘SAIGE/library/SAIGE’

**Comment by jonathonl** [comment]
See https://github.com/statgen/savvy/issues/17#issuecomment-1008921988
