### ISSUE TITLE
new zlib-1.2.12 - another url update required?

### ISSUE THREAD

**Issue by mverkerk** [jonathonl/shrinkwrap#7]
The requirements point at the non-existing:
http://zlib.net/zlib-1.2.11.tar.gz

Probably needs to be updated to current:
http://zlib.net/zlib-1.2.12.tar.gz

**Comment by jonathonl** [comment]
The latest version of shrinkwrap already has the correct URL (see https://github.com/jonathonl/shrinkwrap/blob/v1.2.0/requirements.txt#L3). Archived versions of zlib are located under the `fossils` subdirectory.
